Amit fylo
ColmanDevClub/week-1 pull request #11
Opened 2021-11-24 11:47 UTC by Amit1Paz

דסקטופ ומובייל fylo

2021-11-25 00:10 UTC, Sa-ar requested changes
Looks pretty good. please address the comments

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +    <div class="main">
Is it the right HTML tag to use here?

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +          <div>
Why do you wrap the images with a div tag?

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +            <p class="storageLeft">185</p>
is p tag the best option here?

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +        <div class="whiteBarContainer">
please read about BEM CSS convention

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/style.css
> +/***** options *****/
Great use for a comment!

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/style.css
> +    /* display: flex; */
Is this part of the code or needs to be removed? don't leave unnecessary comments

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/style.css
> +    flex-basis: 65%;
will it work without the display flex property?

2021-11-25 00:10 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/style.css
> +	border-top: 20px solid transparent;
Why did you use this indentation?

2021-11-25 20:28 UTC, Amit1Paz commented on Fylo-FronedMentor-Challenge/index.html
> +          <div>
It was easier for me to control the location and size of the logo this way.
Do you think I need to delete the div and try to do it without it?

2021-11-25 20:28 UTC, Amit1Paz commented on Fylo-FronedMentor-Challenge/style.css
> +@media (max-width: 1050px) {
That's the exact point the two divs are touching each other. I chose this max-width so it will look good on mobile and PC.

2021-11-26 20:57 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/style.css
> +@media (max-width: 1050px) {
Ok so maybe we shouldn't put it under the mobile comment since it might be a bit confusing for the reader

2021-11-26 20:58 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +          <div>
I think it's not necessary and you can clean a bit your HTML with removing this div

2022-11-27 10:29 UTC, closed without merging