Aviel bitton dev
ColmanDevClub/week-1 pull request #12
Opened 2021-11-24 12:47 UTC by AvielBitton

My first HTML page. 
#sa-ar

2021-11-24 14:46 UTC, Sa-ar requested changes
Looks good overall, please take a look over the comments and fix them

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +        <br> <br> <br>
We tend to leave the design part such as spacing to the CSS, so there is no need to add all those `br` tags here

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +        <img src="asset/cloud.png" id="cl1">
Try to use classes whenever possible rather than an id

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +            <iframe src="https://giphy.com/embed/ZVik7pBtu9dNS" width="240" height="134" frameBorder="0"
This is not the way to add images in HTML

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +        <blockquote class="blockquoteDet">
Is this really a block quote?

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +            <h5>LinkedIn |
This is the best way to do it plus we want each of the items to be a link and not a title

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/myCss.css
> +    font-family: 'Montserrat';
Find a way to not duplicate the code like this

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/myCss.css
> +position: absolute;
Use the right indentation for a better readability.

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/myCss.css
> +#cl1{
This is a bad naming. Try to describe what this element is. Also it might be better to use classes here

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/myCss.css
> +right: 300px;
Please check if it still the right thing to do if you see it in a different screen size than yours.
You can check it with every browser's dev tools

2021-11-24 14:46 UTC, Sa-ar commented on First-Html-page/README.md
> +    X hr and footer text = #EAF6F6
Where is the hr tag?

2021-11-25 00:17 UTC, Sa-ar requested changes
The Fylo project doesn't look at all like the image

2021-11-25 00:17 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/fyloCss.css
> +    background-color:  hsl(229, 57%, 11%);
This is a really bad idea. try to understand why and reply to me

2021-11-25 00:17 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/fyloCss.css
> +
why isn't it a background then?

2021-11-26 12:57 UTC, AvielBitton commented
Hi Saar,
I finished the site version (without the mobile version)
@Sa-ar

2021-11-26 20:55 UTC, Sa-ar commented
If the Fylo is not supporting mobile then you didn't finish it.

2021-11-28 16:02 UTC, AvielBitton commented
Hi @Sa-ar 
I also added the mobile version, 
thnx  👍

2021-11-29 15:28 UTC, Sa-ar reviewed
![image](https://user-images.githubusercontent.com/41952193/143895702-29451c8b-6103-4c32-85c8-d79e48a191d0.png)
This is how it looks on my computer... this is not responsive. try to check what you're doing in a browser dev tools

2021-11-29 15:46 UTC, Sa-ar requested changes

2021-11-29 15:46 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/fyloCss.css
> +  width: 400px;
Why just 400 px?

2021-11-29 15:46 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +  <!-- displays site properly based on user's device -->
This is not describing the line below very well

2021-11-29 15:46 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +          <img src="/assets/icon-upload.svg" alt="upload">
this path is going to the root directory which won't always be the same as where assets folder will be

2021-11-29 15:46 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +        <progress color="red" value="815" max="1000"> </progress>
I would try to avoid using the progress element since it can be a bit tricky to work with

2022-11-27 10:29 UTC, closed without merging