Oz
ColmanDevClub/week-1 pull request #18
Opened 2021-11-25 10:28 UTC by ozgemer-git

@Sa-ar

2021-11-25 16:22 UTC, Sa-ar requested changes
Try to use more classes and fewer ids for styling purposes

2021-11-25 16:22 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +                <img id='mountain-img' src='asset/mountain.png'/>
why not use classes?

2021-11-25 16:22 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +                <hr>
very good!

2021-11-25 16:22 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +                <div class='clear'></div>
what is this for?

2021-11-25 16:22 UTC, Sa-ar commented on First-Html-page/style.css
> +h2,h3,h4,h5,h6,h7{
Nice!

2021-11-25 16:22 UTC, Sa-ar commented on Fylo-FronedMentor-Challenge/index.html
> +    <div class='flexbox-item flexbox-item-2'>
try naming you classes better

2021-11-29 14:11 UTC, ozgemer-git commented on First-Html-page/personal-site-challenge.html
> +                <div class='clear'></div>
I used floats for the GIF images, the clear div makes the display appear as wanted

2021-11-29 14:14 UTC, ozgemer-git commented on First-Html-page/personal-site-challenge.html
> +                <img id='mountain-img' src='asset/mountain.png'/>
I thought you should use classes when you want to reuse css and ids when its for a specific element.
If its better to use classes generally, when should i use ids?

2021-11-29 15:25 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +                <img id='mountain-img' src='asset/mountain.png'/>
That's a great question. try to search for the answer and send me what you discovered on slack

2021-11-29 15:26 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +                <div class='clear'></div>
That's OK. Try to use other technics that are more modern next time

2022-11-27 10:29 UTC, closed without merging