First edition
ColmanDevClub/week-1 pull request #6
Opened 2021-11-23 13:35 UTC by xgrm

hi this is the personal-site-challenge

2021-11-23 17:15 UTC, Sa-ar requested changes
Very good! try using a reset CSS too and improve the code

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +        <div id="MyPic"><img /></div>
Where is your pic?

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +      <section>
Why did you use the section tag here?

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +          </div>
Try formatting your code

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/style.css
> +  display: flexbox;
why `flexbox` and what is the difference between this and display flex?

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/style.css
> +  padding-left: 80%;
seems like there might be a better way to locate this id that is not using such high percentage in the padding

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/style.css
> +#bottom_cloud {
try to use less ids and more classes

2021-11-23 17:15 UTC, Sa-ar commented on First-Html-page/style.css
> +h2 {
I think you meant that it will be all the heading tags inside the header tag but this isn't what you did here

2021-11-26 08:50 UTC, xgrm commented on First-Html-page/personal-site-challenge.html
> +        <div id="MyPic"><img /></div>
Sorry I forgot to add

2021-11-26 08:52 UTC, xgrm commented on First-Html-page/personal-site-challenge.html
> +      <section>
Use the section tag to separate articles

2021-11-26 08:54 UTC, xgrm commented on First-Html-page/style.css
> +  display: flexbox;
As I understand it, the difference between them is in the versions. flex is the newer version
I accidentally used flexbox and not flex

2021-11-26 08:57 UTC, xgrm commented on First-Html-page/style.css
> +#bottom_cloud {
Ok, after researching I realized the difference between them. tag can have more than one class. And when I use id I restrict it to use that id only

2021-11-26 09:01 UTC, xgrm commented on First-Html-page/style.css
> +h2 {
What I have tried to do here, is to apply the design only to the headings under the header tag

2021-11-26 09:02 UTC, xgrm commented on First-Html-page/personal-site-challenge.html
> +          </div>
ok(:

2021-11-26 09:23 UTC, xgrm commented on First-Html-page/style.css
> +  padding-left: 80%;
fixit it using flex

2021-11-26 21:02 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +      <section>
my question is why section and not div or something else? do you know the meaning of the section tag?

2021-11-26 21:02 UTC, Sa-ar commented on First-Html-page/style.css
> +  display: flexbox;
great answer :)

2021-11-26 21:05 UTC, Sa-ar commented on First-Html-page/style.css
> +h2 {
so this is not the syntax for that, unfortunately. this will be applied only to h1 that is under a header tag (any header tag) and all h2 tags

2021-11-26 21:11 UTC, Sa-ar requested changes
Please delete all the extra files (`.DS_Store`) too

2021-11-26 21:11 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +      <div class=".copy_right"><p>© DevClub</p></div>
I think you have a typo here in the class

2021-11-26 21:11 UTC, Sa-ar commented on First-Html-page/personal-site-challenge.html
> +        <div><img src="./asset/pic.jpg" class="MyPic" /></div>
You don't have to use the empty div here. I want you to understand why and try to keep all style-related things inside the CSS.

plus you can use your GitHub picture using the URL `github.com/<YOUR_USERNAM>.png`

2021-11-26 21:11 UTC, Sa-ar commented on First-Html-page/style.css
> +  margin: 2px 2px 2px 250px;
250px... I feel like there might be a better way to `position` the clouds

2022-11-27 10:29 UTC, closed without merging